[package]
name = "icm20948_dump"
version = "0.2.0"
edition = "2024"

[dependencies]
cortex-m-rt = "0.7.0"

log = "0.4.27"

embassy-embedded-hal = "0.6.0"
embassy-executor = {version = "0.10.0", features = ["executor-thread", "executor-interrupt"] }
embassy-rp = { version = "0.10.0", features = ["critical-section-impl", "time-driver", "rp235xa", "binary-info"] }
embassy-time = "0.5.1"
usb_console = { path = "../usb_console" }

icm20948-async = "0.4.0"

panic-probe = "1.0.0"
